### ISSUE TITLE
Add gitter badge to redme (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/dav-cli#10]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### DAV CLI

The DAV project you are looking at is DAV CLI. This CLI (command-line interface) tool makes developing applications and solutions that interact with DAV a much more pleasant experience.

### The Issue

Your task for this issue is to add the gitter button which links to the DAV-contributors gitter chat room in the `README.md` file.
Just add the below lines in the `README.md` and look at other DAV projects for the location.
````markdown
[![Gitter](https://img.shields.io/gitter/room/DAVFoundation/DAV-Contributors.svg?style=flat-square)](https://gitter.im/DAVFoundation/DAV-Contributors)
````

### Contributing to DAV CLI

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [DAV CLI GitHub page](https://github.com/DAVFoundation/dav-cli) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-cli.git`
- [ ] **Edit the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-cli](https://github.com/YOUR-USER-NAME/dav-cli)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. 
If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by ghost** [comment]
I would like to work on this issue!

**Comment by cg-cnu** [comment]
Hi @asinghal084,

Thanks for your interest in working on this issue!

We create these *first-timer-only* issues as a way for people who have never contributed to open-source to try their first pull request.

It actually takes a lot more time to write these issues than it would have for us to simply solve them ourselves, but we do that as a way to give many new people a chance to get involved with open source for the first time.

And I think this method works great as a way to make open-source more inviting. It has obviously succeeded in giving you a lot of enthusiasm to contribute😃 

These issues are not about solving a hard programming challenge, but about doing something new for the first time. The programming challenge here is nothing for you, and you have already contributed in the past, so why not move up to the next level now? Find an issue that isn't marked for *first-timers-only*, or find something which you think needs improving, and help us with that.

Thank you again for the enthusiasm, and spending time on helping. We really do appreciate it, and I hope you understand our situation here. Look around the other repos and see if you can find a suitable issue which is not first-timers. Let me know if you need help in the [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors)

**Comment by ghost** [comment]
that's fair :) thank you for giving the opportunities to beginners like me!

**Comment by cg-cnu** [comment]
# This issue is still available for first-timers 🙂

**Comment by MaximeMylle** [comment]
is this still open or claimed? since my first contribution didn't pass, can i try this one then?

**Comment by cg-cnu** [comment]
Hey @MaximeMylle Your issue [here](https://github.com/DAVFoundation/xplore/pull/12) is still pending. There is a merge conflict. Can you try resolving it and finish it.

**Comment by ver-kat** [comment]
I'm very impressed by how thorough your description is!

**Comment by naishu** [comment]
Hi Is the issue still open?

**Comment by cg-cnu** [comment]
Hey @naishu Sorry its claimed by @NeetuGit You can have a look at other repos for beginner issues. Thanks!
