### ISSUE TITLE
Add update notification functionality

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/dav-cli#14]
Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

### DAV CLI

The DAV CLI (command-line interface) tool makes developing applications and solutions that interact with DAV a much more pleasant experience. It allows developers to run fully functioning blockchains on their computer with one command, generate secure keys, and more.

### The Issue

The DAV CLI is usually installed globally on the user's machine. Since there is no good way for users to know when a new version is released, we would like to show them a message when they are using an old version of the CLI.

Luckily, there is a tool that enables this very easily 🎉 [update-notifier](https://github.com/yeoman/update-notifier).

Add the simple integration with update-notifier to the CLI's index.js file.

### Contributing to DAV CLI

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [DAV CLI GitHub page](https://github.com/DAVFoundation/dav-cli) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-cli.git`
- [ ] Run `npm install` to install all dependencies.
- [ ] Run dav-cli by calling `./bin/dav-cli.js`. You can also pass arguments to it (e.g., `./bin/dav-cli.js -s -p 1234`).
- [ ] Now, code, code, code.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-cli](https://github.com/YOUR-USER-NAME/dav-cli)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. 
If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by koutron** [comment]
would love to tackle this

**Comment by TalAter** [comment]
Go for it!

**Comment by koutron** [comment]
Got it working - Right now the updateNotifier function is sitting after all the require statements in the global scope of index.js.  Is that appropriate?  Should I create a program method for the notification?  Here is the snippet below:

```const { generateKeyFile, registerIdentity } = require('./controllers/identity');
const updateNotifier = require('update-notifier');
const pkg = require('../package.json');

updateNotifier({ pkg }).notify();

program.on('--help', () => {

**Comment by TalAter** [comment]
I think placing it in an external file as you suggest might be more elegant.

**Comment by koutron** [comment]
Pull request added at https://github.com/DAVFoundation/dav-cli/pull/18
