### ISSUE TITLE
Add functionality to launch more than one web3 instance

### ISSUE THREAD

**Issue by griffobeid** [DAVFoundation/dav-cli#15]
Thank you for your help ❤️

## What is this project?
DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### DAV CLI
The DAV CLI (command-line interface) tool makes developing applications and solutions that interact with DAV a much more pleasant experience. It allows developers to run fully functioning blockchains on their computer with one command, generate secure keys, and more.

### The Issue

A cool feature of web3 is that it allows multiple instances on the same port. Modify the function `startTestnet()` in `src/controllers/blockchain.js` to receive a second parameter `blocks` that defaults to 1. Then modify the function to launch as many blocks as requested. You will also have to add a flag in `src/index.js` for the blocks and modify the call to `startTestnet()` in `src/index.js`.

### Contributing to DAV CLI
- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the DAV CLI GitHub page and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with $ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-cli.git
- [ ] Run npm install to install all dependencies.
- [ ] Run dav-cli by calling ./bin/dav-cli.js. You can also pass arguments to it (e.g., ./bin/dav-cli.js -s -p 1234).
- [ ] Now, code, code, code.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with $ git push -u origin master
- [ ] Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/dav-cli) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #5)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help
We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our gitter channel. We are always happy to help 😄

**Comment by TalAter** [comment]
Hi @griffobeid 

What's the motivation behind this? Why would developers need more than one instance at a time?

**Comment by griffobeid** [comment]
To be perfectly honest, I don't really know. I was just digging for ideas 😆. I implemented it on my fork pretty simply. Maybe one reason for it would be to test the scalability of the user interface?

**Comment by TalAter** [comment]
I can understand that urge 😆 

But I think the goal of the dav-cli is to abstract away the complexities of learning blockchain, p2p communication, etc. and just let developers focus on solving transportation challenges... so it makes sense to keep things simple, when we have the chance to do that.
