### ISSUE TITLE
Move require to the top of the file (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/dav-cli#20]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

### DAV CLI

The DAV CLI (command-line interface) tool makes developing applications and solutions that interact with DAV a much more pleasant experience. It allows developers to run fully functioning blockchains on their computer with one command, generate secure keys, and more.

### The Issue

The task for this issue is to move the `require` at the line https://github.com/DAVFoundation/dav-cli/blob/master/src/lib/contracts.js#L26 to the top with variable name `DAVContract`.

### Contributing to DAV CLI

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [DAV CLI GitHub page](https://github.com/DAVFoundation/dav-cli) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone https://github.com/YOUR-GITHUB-USER-NAME/dav-cli.git`
- [ ] Run `npm install` to install all dependencies.
- [ ] Run dav-cli by calling `./bin/dav-cli.js`. You can also pass arguments to it (e.g., `./bin/dav-cli.js -s -p 1234`).
- [ ] Now, code, code, code.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-cli](https://github.com/YOUR-USER-NAME/dav-cli)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by Maddiebrighouse** [comment]
Hey I keen to work on this issue as a first timer working on a open source project.

**Comment by TalAter** [comment]
I think the current setup makes sense. There is no need to require that file unless we actually need to `deployContracts`. Not loading it with every call makes the CLI run faster.

See this discussion: https://github.com/alanjames1987/Node.js-Best-Practices/issues/3#issuecomment-63178059

**Comment by TalAter** [comment]
@Maddiebrighouse Thank you for offering your help! I hope you take the chance to pick up one of the other issues and join us in open sourcing 👍😃
