### ISSUE TITLE
Move updateCheckInterval to config

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/dav-cli#23]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

### DAV CLI

The DAV CLI (command-line interface) tool makes developing applications and solutions that interact with DAV a much more pleasant experience. It allows developers to run fully functioning blockchains on their computer with one command, generate secure keys, and more.

### The Issue

The task for this issue is to move `updateCheckInterval: 86400000, // 1 day` in `/src/lib/updateNotifier.js` to `src/config/index.js` as `update_check_interval`. You can look at implementation of `defaultPassword` in `/src/lib/cryptography.js`. 

### Contributing to DAV CLI

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [DAV CLI GitHub page](https://github.com/DAVFoundation/dav-cli) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone https://github.com/YOUR-GITHUB-USER-NAME/dav-cli.git`
- [ ] Run `npm install` to install all dependencies.
- [ ] Run dav-cli by calling `./bin/dav-cli.js`. You can also pass arguments to it (e.g., `./bin/dav-cli.js -s -p 1234`).
- [ ] Now, code, code, code.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-cli](https://github.com/YOUR-USER-NAME/dav-cli)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by brandonlaird** [comment]
I'll claim this issue!

**Comment by codisteinborn** [comment]
Hey, I'd like to help out with this issue if it's still up-for-grabs!

**Comment by srfrnk** [comment]
Sure @codisteinborn - it's yours! Thanks for the help

**Comment by jacksonchui** [comment]
Can I take on this issue if it still has not been completed even though it has been claimed?

**Comment by abhi6998** [comment]
if no one is currently working on it i would like to work on it

**Comment by cg-cnu** [comment]
Thanks for your work on this one @codisteinborn 👏 Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) for more opportunities to contribute. Thanks!
